export const state = {
  originalImageData: null,
  effectsSourceImageData: null,
  effectsSourcePixels: null,
  effectsSourceWidth: 0,
  effectsSourceHeight: 0,
  currentImageData: null,
  selectedPoints: [],
  previewPoint: null,
  restorePoints: [],
  restorePreviewPoint: null,
  lastRestoreBox: null,
  lastBox: null,
  currentDetectorBoxes: [],
  fftDetectorBoxes: [],
  suspectBoxes: [],
  manualBoxes: [],
  manualDetectionActive: false,
  manualPoints: [],
  manualPreviewPoint: null,
  currentFileName: ""
};
